# Generated by Django 5.2.7 on 2025-10-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_updated_at_post_body_en_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='Men haqimda', max_length=200)),
                ('title_en', models.CharField(default='About Me', max_length=200)),
                ('body_uz', models.TextField(default='Men Abdukarim Qarshiyev, dasturlash va texnologiyaga qiziqqan yosh dasturchiman.')),
                ('body_en', models.TextField(default="I'm Abdukarim Qarshiyev, a young developer passionate about technology and software engineering.")),
                ('telegram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('leetcode', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
